env: "dev" # ("dev", "prod")

common:
  project_name: "euromillion"

dev:
  data:
    TABLE: "app/data/bdd.csv"

prod:
  data:
    # input_path: "s3://my-bucket/prod/transactions.csv" # -> Remplacer avec GoogleSheet
