env: "prod" # ("dev", "prod")

common:
  project_name: "euromillion"

dev:
  data:
    TABLE: "uv-env/app/data/BDD.csv"

prod:
  data:
    # input_path: "s3://my-bucket/prod/transactions.csv" # -> Remplacer avec GoogleSheet
