[project]
name = "uv-env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "selenium>=4.40.0",
    "streamlit>=1.53.1",
    "streamlit-extras>=0.7.8",
    "tqdm>=4.67.2",
    "webdriver-manager>=4.0.2",
]
